import{Metadata}from'next';import Link from'next/link';
export const metadata:Metadata={title:'IA para Petshops e Veterinarios: Gestao Inteligente - Automacao IA'};
export default function Page(){const content=`# Seu petshop recebe 30 cães para banho por dia e a recepcionista está sobrecarregada\n\nAnotar nome do pet, raça, serviço e telefone é manual. Cliente liga para remarcar, outro esquece o horário, outro reclama que o shampoo acabou. **15% dos agendamentos viram falta** no fim do mês.\n\n**IA para petshops e veterinários** organiza a bagunça.\n\n## Agendamento inteligente com perfil do pet\n\nCada pet tem particularidades: raça, porte, pelagem, produtos usados, comportamento. IA gerencia tudo.\n\n### Como funciona na prática:\n\n| O que o tutor faz | O que a IA sabe | Resultado |\n|-------------------|-----------------|-----------|\n| Acessa link de agendamento | Pet já cadastrado com foto e histórico | Check-in em 30 segundos |\n| Escolhe serviço (banho, tosa) | Duração do serviço e disponibilidade | Horário sugerido |\n| Confirma horário | Lembrete automático enviado | Zero falta |\n\n**Ferramentas:** **PetManager** ou **Agenda Pet IA**. Tutor não precisa repetir informações a cada visita.\n\n> **Exemplo real:** Uma rede de petshops implementou agendamento com perfil do pet. O tempo de check-in **caiu de 5 minutos para 30 segundos**. A satisfação do cliente **subiu 40%**.\n\n> ---\n> **🚀 Quer automatizar o agendamento do seu petshop?** Teste grátis por 14 dias. [Comece agora](#)\n> ---\n\n## Lembretes de vacinação que geram receita\n\nTutor esquece a vacina do pet. Você perde venda. IA lembra e agenda.\n\n### Alertas automáticos:\n\n| Prazo | Alerta da IA | Ação |\n|-------|--------------|------|\n| 30 dias antes | "V8 do Thor vence em 30 dias. Agende aqui." | Tutor agenda |\n| 15 dias antes | "Faltam 15 dias para a vacina do Thor." | Lembrete reforçado |\n| 7 dias antes | "Vacina do Thor vence semana que vem." | Último aviso |\n\n> **Dica prática:** Configure a IA para enviar 3 lembretes automáticos. A taxa de retorno para vacinação **sobe para 85%**.\n\n## Checklist para organizar seu petshop com IA\n\n- [ ] Implemente agendamento com perfil do pet (histórico, raça, produtos)\n- [ ] Configure lembretes automáticos de vacinação com 30, 15 e 7 dias\n- [ ] Ative check-in digital em 30 segundos\n- [ ] Monitore a redução de faltas e o aumento de receita recorrente`.split('\\n').map((l,i)=>{
  if(l.startsWith('## '))return<h2 key={i} className="text-2xl font-bold mt-10 mb-4 text-white">{l.slice(3)}</h2>;
  if(l.startsWith('### '))return<h3 key={i} className="text-xl font-semibold mt-8 mb-3 text-white">{l.slice(4)}</h3>;
  if(l.startsWith('|'))return<p key={i} className="font-mono text-xs text-slate-400 my-1">{l}</p>;
  if(l.startsWith('- [ ]'))return<p key={i} className="flex items-center gap-2 text-slate-300 my-1"><input type="checkbox" className="w-4 h-4 rounded accent-cyan-500" readOnly/>{l.slice(5)}</p>;
  if(l.startsWith('[')){const m=l.match(/\[(.+?)\]\((.+?)\)/);if(m)return<p key={i} className="my-2"><a href={m[2]} target="_blank" className="text-cyan-400 underline">{m[1]}</a></p>}
  if(!l.trim())return<br key={i}/>;return<p key={i} className="text-slate-300 leading-relaxed mb-2">{l}</p>;});
return(<div className="min-h-screen bg-[#0a0a0f]">
  <div className="border-b border-white/[0.04]"><div className="max-w-3xl mx-auto px-6 py-16">
    <Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-cyan-400 text-sm mb-6">← Voltar</Link>
    <span className="inline-block text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-400 font-medium uppercase tracking-wider mb-4">IA</span>
    <h1 className="text-4xl font-bold leading-tight mb-4 text-white">IA para Petshops e Veterinarios: Gestao Inteligente</h1>
    <div className="flex items-center gap-5 text-sm text-slate-500"><span>2026-05-16</span><span>•</span><span>3 min</span></div>
  </div></div>
  <article className="max-w-3xl mx-auto px-6 py-12"><div className="prose prose-invert max-w-none">{content}</div></article>
</div>);}