import{Metadata}from'next';import Link from'next/link';
export const metadata:Metadata={title:'O Futuro do Trabalho com IA: O Que Muda em 2026 - Automacao IA'};
export default function Page(){const content=`# Você abre o LinkedIn e vê: "IA vai substituir 300 milhões de empregos"\n\nNo meio desse vai-e-vem de opiniões, você fica sem saber se estuda programação, vira especialista em prompt ou simplesmente ignora.\n\nO futuro do trabalho com IA em 2026 não é apocalíptico nem utópico. É prático: algumas funções vão sumir, outras vão se transformar, e novas vão surgir.\n\n## Profissões em risco vs. profissões em alta\n\nNem todo emprego será substituído, mas todo emprego será impactado. A diferença está no tipo de tarefa.\n\n### O que muda em 2026:\n\n| Profissão | Risco | Motivo |\n|-----------|-------|--------|\n| Digitador | Alto | IA transcreve e classifica sozinha |\n| Tradutor simples | Alto | Modelos multilíngues gratuitos |\n| Atendente de call center | Alto | Chatbots resolvem 80% dos chamados |\n| Contador operacional | Médio | Automação de lançamentos fiscais |\n| Programador | Médio | IA gera código, humano revisa |\n| Designer | Baixo | IA cria assets, humano direciona |\n| Médico | Baixo | IA auxilia, diagnóstico final é humano |\n\n## Habilidades que valem ouro em 2026\n\nNão é sobre competir com a IA. É sobre usar a IA como ferramenta. As habilidades mais valorizadas não são técnicas, são humanas.\n\n### O que aprender:\n\n- **Pensamento crítico** — IA entrega dados, você decide o que fazer\n- **Comunicação** — IA escreve, você edita e dá tom\n- **Resolução de problemas** — IA sugere, você valida no mundo real\n- **Gestão de pessoas** — IA não substitui liderança\n\n> ---\n> **🚀 Quer um plano de carreira para 2026?** Baixe o guia gratuito com as 10 habilidades mais requisitadas. [Baixar agora](#)\n> ---\n\n## Como se preparar sem entrar em desespero\n\nA IA não vai te substituir. Mas uma pessoa que sabe usar IA vai. A diferença é quem aprende a ferramenta primeiro.\n\n### Plano de 30 dias:\n\n- **Semana 1:** Escolha uma IA (DeepSeek, ChatGPT ou Claude) e use todo dia\n- **Semana 2:** Automatize uma tarefa repetitiva do seu trabalho com Make ou Zapier\n- **Semana 3:** Crie um projeto pessoal usando IA (site, roteiro, planilha inteligente)\n- **Semana 4:** Ensine alguém a usar a ferramenta que você aprendeu\n\n> **Exemplo real:** Um analista financeiro aprendeu a usar IA para gerar relatórios mensais. O que levava 8 horas passou a levar 1 hora. Ele usou o tempo extra para analisar dados mais profundos e foi promovido em 6 meses.\n\n## Checklist para se preparar para o futuro do trabalho\n\n- [ ] Identifique tarefas repetitivas no seu trabalho atual\n- [ ] Escolha UMA ferramenta de IA para aprender esta semana\n- [ ] Automatize pelo menos uma tarefa usando Make ou Zapier\n- [ ] Compartilhe seu aprendizado com colegas (ensinar fixa o conhecimento)`.split('\\n').map((l,i)=>{
  if(l.startsWith('## '))return<h2 key={i} className="text-2xl font-bold mt-10 mb-4 text-white">{l.slice(3)}</h2>;
  if(l.startsWith('### '))return<h3 key={i} className="text-xl font-semibold mt-8 mb-3 text-white">{l.slice(4)}</h3>;
  if(l.startsWith('|'))return<p key={i} className="font-mono text-xs text-slate-400 my-1">{l}</p>;
  if(l.startsWith('- [ ]'))return<p key={i} className="flex items-center gap-2 text-slate-300 my-1"><input type="checkbox" className="w-4 h-4 rounded accent-cyan-500" readOnly/>{l.slice(5)}</p>;
  if(l.startsWith('[')){const m=l.match(/\[(.+?)\]\((.+?)\)/);if(m)return<p key={i} className="my-2"><a href={m[2]} target="_blank" className="text-cyan-400 underline">{m[1]}</a></p>}
  if(!l.trim())return<br key={i}/>;return<p key={i} className="text-slate-300 leading-relaxed mb-2">{l}</p>;});
return(<div className="min-h-screen bg-[#0a0a0f]">
  <div className="border-b border-white/[0.04]"><div className="max-w-3xl mx-auto px-6 py-16">
    <Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-cyan-400 text-sm mb-6">← Voltar</Link>
    <span className="inline-block text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-400 font-medium uppercase tracking-wider mb-4">IA</span>
    <h1 className="text-4xl font-bold leading-tight mb-4 text-white">O Futuro do Trabalho com IA: O Que Muda em 2026</h1>
    <div className="flex items-center gap-5 text-sm text-slate-500"><span>2026-05-16</span><span>•</span><span>3 min</span></div>
  </div></div>
  <article className="max-w-3xl mx-auto px-6 py-12"><div className="prose prose-invert max-w-none">{content}</div></article>
</div>);}