import{Metadata}from'next';import Link from'next/link';
export const metadata:Metadata={title:'IA para Dentistas: Automatize Agendamento e Confirmacao - Automacao IA'};
export default function Page(){const content=`# Paciente marca consulta e não aparece. Você perde R$ 4.000 por mês\n\nSegunda-feira 14h. Paciente confirmou. Você preparou o consultório. Ele não vem. Você perdeu 40 minutos de agenda. Outro paciente que poderia ter sido atendido ficou sem vaga.\n\nNo fim do mês, **20 faltas**. Horários vazios que poderiam estar ocupados.\n\n**IA para dentistas** resolve o problema de faltas e otimiza sua agenda. São 3 áreas que entregam resultado imediato.\n\n## Agendamento que o paciente faz sozinho em 30 segundos\n\nPaciente quer marcar, mas seu horário disponível não encaixa. Você perde o paciente. IA otimiza a agenda em tempo real.\n\n### Como funciona na prática:\n\n| O que o paciente quer | O que a IA mostra | Resultado |\n|-----------------------|-------------------|-----------|\n| "Segunda à tarde" | Horários compatíveis com procedimentos longos | Agenda otimizada |\n| "Limpeza, qualquer horário" | Vagas curtas entre procedimentos | Aproveita gaps |\n| "Canal, prefiro manhã" | Blocos de 2h disponíveis pela manhã | Procedimento encaixa |\n\n**Ferramentas:** **ClinicWeb** ou **Dental Office** com módulo de IA. Paciente acessa link, escolhe e confirma em 30 segundos.\n\n> **Exemplo real:** Uma clínica em São Paulo implementou agendamento inteligente. A taxa de faltas **caiu de 20% para 5%** em 3 meses. O faturamento **subiu R$ 4.000/mês**.\n\n---\n\n> **🚀 Automatize sua clínica em 1 dia.** Teste grátis por 14 dias. [Comece agora](#)\n\n---\n\n## Lembretes que reduzem faltas em 70%\n\nPaciente confirma e esquece. Com IA, o lembrete é personalizado e enviado no melhor horário.\n\n### Como configurar:\n\n- **48h antes:** "Confirme sua consulta de segunda"\n- **24h antes:** "Lembrete: consulta amanhã às 14h"\n- **2h antes:** "Estamos te esperando!"\n- **Se não confirmar:** "Vaga liberada para outro paciente"\n\n## Gestão financeira que não deixa dinheiro na mesa\n\nProcedimento feito, pagamento pendente. IA cobra automaticamente e oferece parcelamento.\n\n**Benefícios:**\n- Cobrança automática pós-procedimento\n- Parcelamento no cartão em segundos\n- Relatório de inadimplência semanal\n- Ofertas personalizadas para reativar pacientes\n\n## Checklist para modernizar seu consultório\n\n- [ ] Configure agendamento online com IA\n- [ ] Ative lembretes automáticos personalizados\n- [ ] Implemente cobrança recorrente automática\n- [ ] Monitore taxa de faltas semanalmente`.split('\\n').map((l,i)=>{
  if(l.startsWith('## '))return<h2 key={i} className="text-2xl font-bold mt-10 mb-4 text-white">{l.slice(3)}</h2>;
  if(l.startsWith('### '))return<h3 key={i} className="text-xl font-semibold mt-8 mb-3 text-white">{l.slice(4)}</h3>;
  if(l.startsWith('|'))return<p key={i} className="font-mono text-xs text-slate-400 my-1">{l}</p>;
  if(l.startsWith('- [ ]'))return<p key={i} className="flex items-center gap-2 text-slate-300 my-1"><input type="checkbox" className="w-4 h-4 rounded accent-cyan-500" readOnly/>{l.slice(5)}</p>;
  if(l.startsWith('[')){const m=l.match(/\[(.+?)\]\((.+?)\)/);if(m)return<p key={i} className="my-2"><a href={m[2]} target="_blank" className="text-cyan-400 underline">{m[1]}</a></p>}
  if(!l.trim())return<br key={i}/>;return<p key={i} className="text-slate-300 leading-relaxed mb-2">{l}</p>;});
return(<div className="min-h-screen bg-[#0a0a0f]">
  <div className="border-b border-white/[0.04]"><div className="max-w-3xl mx-auto px-6 py-16">
    <Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-cyan-400 text-sm mb-6">\u2190 Voltar</Link>
    <span className="inline-block text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-400 font-medium uppercase tracking-wider mb-4">IA</span>
    <h1 className="text-4xl font-bold leading-tight mb-4 text-white">IA para Dentistas: Automatize Agendamento e Confirmacao</h1>
    <div className="flex items-center gap-5 text-sm text-slate-500"><span>2026-05-16</span><span>\u2022</span><span>3 min</span></div>
  </div></div>
  <article className="max-w-3xl mx-auto px-6 py-12"><div className="prose prose-invert max-w-none">{content}</div></article>
</div>);}