import{Metadata}from'next';import Link from'next/link';
export const metadata:Metadata={title:'IA para Entregadores: Roteirizacao e Multiplos Apps - Automacao IA'};
export default function Page(){const content=`# Você roda 120 km por dia e ganha R$ 150. Sobra R$ 80 depois da gasolina\n\nPedido chega: 8 km para buscar, 5 km para entregar. R$ 12. Você aceita porque não sabe se virá outro. Passa em frente a 3 restaurantes com pedidos prontos que poderia ter pego.\n\n**IA para entregadores** otimiza rotas e gerencia múltiplos apps ao mesmo tempo.\n\n## Roteirização inteligente que agrupa entregas\n\nFazer uma entrega por vez é ineficiente. IA agrupa pedidos que estão no mesmo caminho.\n\n### Como funciona na prática:\n\n| O que a IA analisa | O que sugere | Resultado |\n|--------------------|--------------|-----------|\n| Sua localização | Pegar pedido A (1 km) + pedido B (2 km) | 2 entregas, 7 km |\n| Pedidos em todos os apps | Entregar A primeiro (3 km), depois B (1 km) | R$ 24 no total |\n| Destino de cada entrega | Rota otimizada sem voltar | Menos gasolina |\n\n**Ferramentas:** **Entregador Inteligente** ou **Rota Fácil**. IA analisa pedidos disponíveis em todos os apps e sugere a melhor combinação.\n\n> **Exemplo real:** Um entregador em BH usava roteirização inteligente. As entregas por hora **subiram de 2 para 4**. A quilometragem diária **caiu de 120 km para 80 km**. O lucro líquido **aumentou 60%**.\n\n> ---\n> **🚀 Quer otimizar suas entregas com IA?** Teste grátis por 14 dias. [Comece agora](#)\n> ---\n\n## Gestão de múltiplos apps em um só lugar\n\nVocê tem 3 apps abertos, cada um com pedidos diferentes. Perde tempo alternando entre eles.\n\n### O que a IA faz:\n\n- **Agrupa pedidos** de todos os apps em uma única tela\n- **Prioriza** entregas com melhor relação distância/valor\n- **Calcula** a rota ideal combinando todos os pedidos\n- **Notifica** quando um pedido novo vale a pena aceitar\n\n> **Dica prática:** Configure a IA para aceitar automaticamente pedidos acima de R$ 15 que estejam no mesmo raio de 3 km. Reduza o tempo de decisão e aumente a produtividade.\n\n## Checklist para aumentar seu lucro como entregador\n\n- [ ] Ative a roteirização inteligente para agrupar entregas no mesmo caminho\n- [ ] Configure a gestão de múltiplos apps em uma única tela\n- [ ] Defina critérios mínimos de valor por quilômetro para aceitar pedidos\n- [ ] Monitore a redução de quilometragem e o aumento de entregas por hora`.split('\\n').map((l,i)=>{
  if(l.startsWith('## '))return<h2 key={i} className="text-2xl font-bold mt-10 mb-4 text-white">{l.slice(3)}</h2>;
  if(l.startsWith('### '))return<h3 key={i} className="text-xl font-semibold mt-8 mb-3 text-white">{l.slice(4)}</h3>;
  if(l.startsWith('|'))return<p key={i} className="font-mono text-xs text-slate-400 my-1">{l}</p>;
  if(l.startsWith('- [ ]'))return<p key={i} className="flex items-center gap-2 text-slate-300 my-1"><input type="checkbox" className="w-4 h-4 rounded accent-cyan-500" readOnly/>{l.slice(5)}</p>;
  if(l.startsWith('[')){const m=l.match(/\[(.+?)\]\((.+?)\)/);if(m)return<p key={i} className="my-2"><a href={m[2]} target="_blank" className="text-cyan-400 underline">{m[1]}</a></p>}
  if(!l.trim())return<br key={i}/>;return<p key={i} className="text-slate-300 leading-relaxed mb-2">{l}</p>;});
return(<div className="min-h-screen bg-[#0a0a0f]">
  <div className="border-b border-white/[0.04]"><div className="max-w-3xl mx-auto px-6 py-16">
    <Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-cyan-400 text-sm mb-6">← Voltar</Link>
    <span className="inline-block text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-400 font-medium uppercase tracking-wider mb-4">IA</span>
    <h1 className="text-4xl font-bold leading-tight mb-4 text-white">IA para Entregadores: Roteirizacao e Multiplos Apps</h1>
    <div className="flex items-center gap-5 text-sm text-slate-500"><span>2026-05-16</span><span>•</span><span>3 min</span></div>
  </div></div>
  <article className="max-w-3xl mx-auto px-6 py-12"><div className="prose prose-invert max-w-none">{content}</div></article>
</div>);}