import{Metadata}from'next';import Link from'next/link';
export const metadata:Metadata={title:'IA para Professores: Ferramentas que Transformam o Ensino - Automacao IA'};
export default function Page(){const content=`# Você passa o fim de semana corrigindo 40 redações\n\nPrepara aula até meia-noite. Cria atividades, provas, listas de exercício. O trabalho nunca acaba. A parte burocrática toma o tempo que deveria ser dos alunos.\n\n**IA para professores** não substitui seu olhar pedagógico. Ela elimina o trabalho repetitivo que consome horas.\n\n## Planos de aula automáticos\n\nCriar plano de aula do zero toda semana cansa. Com IA, você gera um plano completo em 2 minutos.\n\n### Como funciona na prática:\n\n| O que você pede | O que a IA gera | Seu trabalho |\n|-----------------|-----------------|--------------|\n| "Plano de 50 min sobre [tema] para [série]" | Objetivo, introdução, atividade prática, avaliação | Ajustar tom e profundidade |\n| "Cronograma do semestre inteiro" | Aulas organizadas por semana | Revisar uma vez |\n| "Atividade complementar para alunos avançados" | Exercícios diferenciados | Aplicar em sala |\n\n**Ferramentas:** **ChatGPT** ou **Claude**. Plano de aula completo em minutos.\n\n> **Dica prática:** Salve os planos gerados em um drive. No início do ano, peça para a IA criar o cronograma do semestre inteiro. Você ajusta uma vez e usa o ano todo.\n\n---\n\n> **🚀 Quer automatizar a preparação das suas aulas?** Teste grátis por 14 dias. [Comece agora](#)\n\n---\n\n## Correção de redações e provas com IA\n\nCorrigir 40 redações manualmente toma um fim de semana. IA faz o primeiro filtro.\n\n### Como funciona:\n\n| O que a IA avalia | O que sinaliza | Seu trabalho |\n|-------------------|----------------|--------------|\n| Coerência, coesão, gramática | Nota sugerida | Validar e ajustar |\n| Ortografia, concordância | Erros destacados | Revisar casos duvidosos |\n| Tema, argumentação, conclusão | Estrutura avaliada | Dar feedback personalizado |\n\n## Criação de provas e exercícios variados\n\nCriar prova diferente para cada turma é repetitivo. IA gera versões variadas.\n\n**Como funciona:**\n- Define tema e nível de dificuldade\n- IA gera 3 versões diferentes\n- Inclui gabarito automático\n- Você só revisa e aplica\n\n## Checklist para ganhar tempo como professor\n\n- [ ] Configure planos de aula automáticos\n- [ ] Ative correção de redações com IA\n- [ ] Implemente criação de provas variadas\n- [ ] Reduza preparação de aula em 80%`.split('\\n').map((l,i)=>{
  if(l.startsWith('## '))return<h2 key={i} className="text-2xl font-bold mt-10 mb-4 text-white">{l.slice(3)}</h2>;
  if(l.startsWith('### '))return<h3 key={i} className="text-xl font-semibold mt-8 mb-3 text-white">{l.slice(4)}</h3>;
  if(l.startsWith('|'))return<p key={i} className="font-mono text-xs text-slate-400 my-1">{l}</p>;
  if(l.startsWith('- [ ]'))return<p key={i} className="flex items-center gap-2 text-slate-300 my-1"><input type="checkbox" className="w-4 h-4 rounded accent-cyan-500" readOnly/>{l.slice(5)}</p>;
  if(l.startsWith('[')){const m=l.match(/\[(.+?)\]\((.+?)\)/);if(m)return<p key={i} className="my-2"><a href={m[2]} target="_blank" className="text-cyan-400 underline">{m[1]}</a></p>}
  if(!l.trim())return<br key={i}/>;return<p key={i} className="text-slate-300 leading-relaxed mb-2">{l}</p>;});
return(<div className="min-h-screen bg-[#0a0a0f]">
  <div className="border-b border-white/[0.04]"><div className="max-w-3xl mx-auto px-6 py-16">
    <Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-cyan-400 text-sm mb-6">\u2190 Voltar</Link>
    <span className="inline-block text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-400 font-medium uppercase tracking-wider mb-4">IA</span>
    <h1 className="text-4xl font-bold leading-tight mb-4 text-white">IA para Professores: Ferramentas que Transformam o Ensino</h1>
    <div className="flex items-center gap-5 text-sm text-slate-500"><span>2026-05-16</span><span>\u2022</span><span>3 min</span></div>
  </div></div>
  <article className="max-w-3xl mx-auto px-6 py-12"><div className="prose prose-invert max-w-none">{content}</div></article>
</div>);}