import Link from "next/link";
import{ArrowLeft}from"lucide-react";
const SLUGS={
automacao:[
{slug:"automacao-atendimento-ia-hoteis",t:"Como Automatizar Atendimento em Hotéis e Pousadas com IA",d:"2026-05-16"},
{slug:"automacao-atendimento-medico-ia",t:"IA no Atendimento Medico: Chatbots e Triagem",d:"2026-05-16"},
{slug:"automacao-clinicas-medicas-ia",t:"Automatizacao de Clinicas Medicas com IA",d:"2026-05-16"},
{slug:"automacao-condominios-gestao-ia",t:"Gestao de Condominios com IA: Automatize Tudo",d:"2026-05-16"},
{slug:"automacao-ecommerce-shopify-ia",t:"Como Automatizar sua Loja Shopify com IA",d:"2026-05-16"},
{slug:"automacao-email-marketing-ia",t:"Como Automatizar Email Marketing com IA",d:"2026-05-16"},
{slug:"automacao-eventos-cerimonial-ia",t:"Como Automatizar Eventos e Cerimonial com IA",d:"2026-05-16"},
{slug:"automacao-faturamento-notas-fiscais",t:"Automatize Faturamento e Notas Fiscais com IA",d:"2026-05-16"},
{slug:"automacao-financeira-pequena-empresa",t:"Automação Financeira com IA para Pequenas Empresas",d:"2026-05-16"},
{slug:"automacao-ia-oportunidade-2026",t:"A Única Oportunidade de Automação com IA Que Vale Seu Tempo em 2026",d:"2026-05-15"},
{slug:"automacao-marketing-digital-ia",t:"Como Automatizar seu Marketing Digital com IA",d:"2026-05-16"},
{slug:"automacao-oficinas-mecanicas-ia",t:"Automacao de Oficinas Mecanicas com IA",d:"2026-05-16"},
{slug:"automacao-processos-rpa-ia",t:"RPA com IA: Como Automatizar Processos Repetitivos sem Programar",d:"2026-05-16"},
{slug:"automacao-rh-contratacao-ia",t:"Como Automatizar RH e Contratacao com IA",d:"2026-05-16"},
{slug:"automacao-suporte-tecnico-ti-ia",t:"Automatize o Suporte Tecnico de TI com IA",d:"2026-05-16"},
{slug:"ferramentas-automacao-pequenos-negocios",t:"As 5 Melhores Ferramentas de Automacao para Pequenos Negocios em 2026",d:"2026-05-15"},
{slug:"futuro-trabalho-ia-automacao",t:"O Futuro do Trabalho com IA: O Que Muda em 2026",d:"2026-05-16"},
{slug:"ia-delivery-restaurantes-automacao",t:"IA no Delivery: Automatize Pedidos e Entregas do Seu Restaurante",d:"2026-05-16"},
{slug:"ia-lavanderias-automacao",t:"IA para Lavanderias: Pedidos e Entregas Automaticos",d:"2026-05-16"},
{slug:"ia-para-advogados-automacao-juridica",t:"IA para Advogados: Automatize Documentos Juridicos",d:"2026-05-16"},
{slug:"ia-redes-sociais-automacao-posts",t:"Automatize suas Redes Sociais com IA em 2026",d:"2026-05-16"},
{slug:"ia-vendas-b2b-automacao",t:"IA para vendas B2B: como automatizar prospeccao e follow-up",d:"2026-05-16"},
],
ferramentas:[
{slug:"chatgpt-vs-deepseek-vs-claude",t:"ChatGPT vs DeepSeek vs Claude: Qual a Melhor IA em 2026",d:"2026-05-16"},
{slug:"ia-design-grafico-ferramentas",t:"IA no Design Grafico: Ferramentas que Todo Designer Precisa",d:"2026-05-16"},
{slug:"ia-escritores-criativos-ferramentas",t:"IA para Escritores: Ferramentas que Potencializam a Criatividade",d:"2026-05-16"},
{slug:"ia-gestao-projetos-ferramentas",t:"IA na Gestao de Projetos: Ferramentas Essenciais",d:"2026-05-16"},
{slug:"melhores-apis-ia-desenvolvedores",t:"Melhores APIs de IA para desenvolvedores integrarem em 2026",d:"2026-05-16"},
{slug:"melhores-prompts-chatgpt-negocios",t:"10 Melhores Prompts do ChatGPT para Pequenos Negocios",d:"2026-05-16"},
{slug:"nocode-lowcode-ferramentas-gratis",t:"No-Code vs Low-Code: Melhores Ferramentas Gratis",d:"2026-05-16"},
{slug:"produtividade-ferramentas-gratis-ia",t:"10 Ferramentas de IA Gratis que Vão Dobrar Sua Produtividade",d:"2026-05-16"},
],
saude:[
{slug:"ia-academias-personal-trainer",t:"IA para Academias: Treinos Personalizados e Gestao",d:"2026-05-16"},
{slug:"ia-atendimento-clinicas-dentistas",t:"IA para Dentistas: Automatize Agendamento e Confirmacao",d:"2026-05-16"},
{slug:"ia-farmacias-drogaria-gestao",t:"IA para Farmacias: Gestao de Estoque e Validade",d:"2026-05-16"},
],
negocios:[
{slug:"ia-agricultura-agronegocio",t:"IA no Agronegocio: Automacao para o Campo",d:"2026-05-16"},
{slug:"ia-pequenos-negocios-guia-completo",t:"Guia Completo de IA para Pequenos Negocios em 2026",d:"2026-05-16"},
{slug:"monetizacao-blog-adsense-afiliados",t:"Guia de Monetizacao: AdSense e Afiliados para Blogs",d:"2026-05-16"},
],
ia:[
{slug:"ia-analise-dados-empresa",t:"Como Usar IA para Analisar Dados da Sua Empresa",d:"2026-05-16"},
{slug:"ia-artistas-digitais-nft",t:"IA para Artistas Digitais: Criacao e Venda de NFT",d:"2026-05-16"},
{slug:"ia-atendimento-cliente-chatbot",t:"Chatbot com IA para Atendimento ao Cliente",d:"2026-05-16"},
{slug:"ia-atendimento-cliente-transformacao-2026",t:"Como a IA Esta Transformando o Atendimento ao Cliente em 2026",d:"2026-05-16"},
{slug:"ia-atendimento-whatsapp-reduzir-tempo",t:"Como Reduzir 80% do Tempo de Atendimento com IA no WhatsApp",d:"2026-05-15"},
{slug:"ia-autonomos-profissionais-liberais",t:"IA para Autonomos: Como Multiplicar Seus Ganhos",d:"2026-05-16"},
{slug:"ia-criacao-sites-landing-pages",t:"Como Criar Sites e Landing Pages com IA em Minutos",d:"2026-05-16"},
{slug:"ia-criar-imagens-blog-thumbnails",t:"Como Criar Imagens e Thumbnails com IA para Blog e YouTube",d:"2026-05-16"},
{slug:"ia-criar-posts-blog-automatico",t:"Como Criar Posts de Blog com IA em 5 Minutos (Sem Escrever Nada)",d:"2026-05-15"},
{slug:"ia-edicao-video-automatica",t:"IA para Edicao de Video: Automatize Cortes e Legendas",d:"2026-05-16"},
{slug:"ia-gestao-tempo-empreendedor",t:"Como usar IA para gestao de tempo de empreendedores",d:"2026-05-16"},
{slug:"ia-imobiliarias-locacao-venda",t:"IA para Imobiliarias: Automatize Locacao e Vendas",d:"2026-05-16"},
{slug:"ia-loja-roupa-moda-gestao",t:"IA para Lojas de Roupa: Estoque e Tendencias",d:"2026-05-16"},
{slug:"ia-mercados-supermercados",t:"IA para Supermercados: Precificacao e Reposicao",d:"2026-05-16"},
{slug:"ia-musicos-produtores-musicais",t:"IA para Musicos: Composicao e Producao Musical",d:"2026-05-16"},
{slug:"ia-para-arquitetos-engenheiros",t:"IA para Arquitetos e Engenheiros: Projetos Inteligentes",d:"2026-05-16"},
{slug:"ia-para-bares-restaurantes-gestao",t:"IA na Gestao de Bares e Restaurantes",d:"2026-05-16"},
{slug:"ia-para-chefes-cozinheiros",t:"IA para Chefs: Cardapios, Receitas e Precificacao",d:"2026-05-16"},
{slug:"ia-para-contadores-escritorios",t:"IA para Contadores: Automatize seu Escritorio Contabil",d:"2026-05-16"},
{slug:"ia-para-corretores-imoveis",t:"IA para Corretores de Imoveis: Venda Mais Rapido",d:"2026-05-16"},
{slug:"ia-para-eletricistas-prestadores",t:"IA para Eletricistas: Orcamentos e Agendamento",d:"2026-05-16"},
{slug:"ia-para-entregadores-motoboys",t:"IA para Entregadores: Roteirizacao e Multiplos Apps",d:"2026-05-16"},
{slug:"ia-para-fotografos-edicao",t:"IA para Fotografos: Edicao e Organizacao Automatica",d:"2026-05-16"},
{slug:"ia-para-hoteis-fazenda-pousadas",t:"IA para Hoteis Fazenda: Experiencia do Hospede",d:"2026-05-16"},
{slug:"ia-para-igrejas-eventos",t:"IA para Igrejas: Automatize Eventos e Comunicacao",d:"2026-05-16"},
{slug:"ia-para-padarias-confeitarias",t:"IA para Padarias: Controle de Producao e Estoque",d:"2026-05-16"},
{slug:"ia-para-petshops-veterinarios",t:"IA para Petshops e Veterinarios: Gestao Inteligente",d:"2026-05-16"},
{slug:"ia-para-professores-ensino",t:"IA para Professores: Ferramentas que Transformam o Ensino",d:"2026-05-16"},
{slug:"ia-para-restaurantes-delivery",t:"IA para Restaurantes: Cardapio Inteligente e Automacao",d:"2026-05-16"},
{slug:"ia-para-sorveterias-gestao",t:"IA para Sorveterias: Producao e Vendas Inteligentes",d:"2026-05-16"},
{slug:"ia-para-streamers-lives",t:"IA para Streamers: Automatize Alertas e Moderacao",d:"2026-05-16"},
{slug:"ia-para-taxistas-motoristas-app",t:"IA para Motoristas de App: Otimize suas Corridas",d:"2026-05-16"},
{slug:"ia-podcasters-producao-audio",t:"IA para Podcasters: Gravacao, Edicao e Distribuicao",d:"2026-05-16"},
{slug:"ia-postos-gasolina-gestao",t:"IA para Postos de Gasolina: Automacao e Fidelizacao",d:"2026-05-16"},
{slug:"ia-saloes-beleza-barbearias",t:"IA para Saloes e Barbearias: Agendamento e Fidelizacao",d:"2026-05-16"},
{slug:"ia-startups-mvp-produto",t:"IA para Startups: Do MVP ao Lancamento em Tempo Recorde",d:"2026-05-16"},
{slug:"ia-transporte-logistica-frota",t:"IA na Logistica: Otimize Rotas e Entregas",d:"2026-05-16"},
{slug:"planilhas-inteligentes-ia-google-sheets",t:"Planilhas Inteligentes: Como Automatizar Relatorios com IA e Google Sheets",d:"2026-05-15"},
{slug:"seguranca-digital-ia-protecao",t:"Seguranca Digital com IA: Proteja sua Empresa",d:"2026-05-16"},
],
marketing:[
{slug:"ia-influenciadores-digitais",t:"IA para Influenciadores: Conteudo, Metricas e Monetizacao",d:"2026-05-16"},
{slug:"ia-traducao-conteudo-multilingue",t:"IA para Traducao: Como Criar Conteudo Multilingue",d:"2026-05-16"},
{slug:"ia-youtubers-criadores-conteudo",t:"IA para YouTubers: Roteiro, Edicao e SEO de Videos",d:"2026-05-16"},
],
};
export default function Category({params}:{params:{slug:string}}){const s=params.slug;const items=SLUGS[s]||[];return(<div className="min-h-screen bg-[#0a0a0f]"><div className="border-b border-white/[0.04]"><div className="max-w-6xl mx-auto px-6 py-12"><Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-cyan-400 text-sm mb-4"><ArrowLeft className="w-3 h-3"/>Voltar</Link><h1 className="text-3xl font-bold text-white capitalize">{s}</h1><p className="text-slate-400 mt-2">{items.length} artigos</p></div></div><div className="max-w-6xl mx-auto px-6 py-8"><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{items.map(p=>(<Link key={p.slug} href={`/blog/${p.slug}`} className="card-hover group p-5 rounded-2xl glass border border-white/[0.04]"><span className="text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-400">{s}</span><h3 className="font-semibold mt-2 mb-1 text-sm text-white group-hover:text-cyan-400">{p.t}</h3><div className="text-[10px] text-slate-600">{p.d}</div></Link>))}</div></div></div>);}