import{Metadata}from'next';import Link from'next/link';
export const metadata:Metadata={title:'Planilhas Inteligentes: Como Automatizar Relatorios com IA e Google Sheets - Automacao IA'};
export default function Page(){const content=`# Você baixa dados, cria gráficos, escreve resumos, formata células. Toda semana o mesmo processo\n\nRelatórios são úteis, mas o trabalho manual de produzi-los é repetitivo. Erro de digitação, fórmula quebrada, dado desatualizado. Automatizar corta isso para zero.\n\nConectar planilhas ao **Make** e **DeepSeek** transforma dados brutos em relatórios prontos em segundos.\n\n## O que você vai precisar\n\n### Ferramentas necessárias:\n\n| Ferramenta | Função | Custo |\n|------------|--------|-------|\n| Google Sheets | Dados vivos | Grátis |\n| Make | Orquestrador | Grátis (1000 ops/mês) |\n| DeepSeek API | IA para analisar | $0,27/1M tokens |\n| Google Drive API | Conexão | Grátis |\n\n## Passo a passo\n\n### 1. Prepare sua planilha\n\nOrganize os dados em formato tabular. Primeira linha com cabeçalhos. Sem células mescladas.\n\n**Exemplo de estrutura:**\n\n| Data | Vendas | Produto | Região |\n|------|--------|---------|--------|\n| 01/01 | 1500 | Camisa | SP |\n| 01/01 | 2300 | Calçado | RJ |\n\n> **Regra:** Dados limpos = relatório preciso. Dados bagunçados = resultado errado.\n\n### 2. Crie o cenário no Make\n\n- **Trigger:** Agendamento (toda segunda 8h) ou botão na planilha\n- **Módulo Google Sheets:** Busca linhas da planilha\n- **Módulo DeepSeek:** Envia dados para análise com prompt específico\n- **Módulo Google Docs:** Gera relatório formatado\n\n---\n\n> **🚀 Quer automatizar seus relatórios com IA?** Teste grátis por 14 dias. [Comece agora](#)\n\n---\n\n### 3. Configure o prompt do DeepSeek\n\nO prompt define a qualidade do relatório. Seja específico.\n\n**Prompt que funciona:**\n\n\`\`\`\nAnalise estes dados de vendas do período [data].\nGere: 1) Resumo executivo (3 linhas)\n2) Top 3 produtos por receita\n3) Região com maior crescimento\n4) 1 recomendação acionável\nFormato: texto limpo, sem markdown.\n\`\`\`\n\n### 4. Automatize a entrega\n\nO relatório pronto precisa chegar a quem usa.\n\n**Canais de entrega:**\n- **E-mail:** Enviar para lista de gestores\n- **Slack/Teams:** Postar no canal de resultados\n- **Google Drive:** Salvar com data no nome do arquivo\n- **Dashboard:** Atualizar painel no Google Data Studio\n\n## Checklist para automatizar relatórios\n\n- [ ] Organize dados em formato tabular limpo\n- [ ] Conecte Google Sheets ao Make\n- [ ] Configure prompt do DeepSeek para análise\n- [ ] Defina trigger (agendamento ou manual)\n- [ ] Configure canal de entrega (e-mail, Slack, Drive)\n- [ ] Teste com dados reais antes de ativar`.split('\\n').map((l,i)=>{
  if(l.startsWith('## '))return<h2 key={i} className="text-2xl font-bold mt-10 mb-4 text-white">{l.slice(3)}</h2>;
  if(l.startsWith('### '))return<h3 key={i} className="text-xl font-semibold mt-8 mb-3 text-white">{l.slice(4)}</h3>;
  if(l.startsWith('|'))return<p key={i} className="font-mono text-xs text-slate-400 my-1">{l}</p>;
  if(l.startsWith('- [ ]'))return<p key={i} className="flex items-center gap-2 text-slate-300 my-1"><input type="checkbox" className="w-4 h-4 rounded accent-cyan-500" readOnly/>{l.slice(5)}</p>;
  if(l.startsWith('[')){const m=l.match(/\[(.+?)\]\((.+?)\)/);if(m)return<p key={i} className="my-2"><a href={m[2]} target="_blank" className="text-cyan-400 underline">{m[1]}</a></p>}
  if(!l.trim())return<br key={i}/>;return<p key={i} className="text-slate-300 leading-relaxed mb-2">{l}</p>;});
return(<div className="min-h-screen bg-[#0a0a0f]">
  <div className="border-b border-white/[0.04]"><div className="max-w-3xl mx-auto px-6 py-16">
    <Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-cyan-400 text-sm mb-6">\u2190 Voltar</Link>
    <span className="inline-block text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-400 font-medium uppercase tracking-wider mb-4">IA</span>
    <h1 className="text-4xl font-bold leading-tight mb-4 text-white">Planilhas Inteligentes: Como Automatizar Relatorios com IA e Google Sheets</h1>
    <div className="flex items-center gap-5 text-sm text-slate-500"><span>2026-05-15</span><span>\u2022</span><span>3 min</span></div>
  </div></div>
  <article className="max-w-3xl mx-auto px-6 py-12"><div className="prose prose-invert max-w-none">{content}</div></article>
</div>);}