import{Metadata}from'next';import Link from'next/link';
export const metadata:Metadata={title:'IA para Advogados: Automatize Documentos Juridicos - Automacao IA'};
export default function Page(){const content=`# Você passa horas redigindo contratos que são 90% iguais\n\nPetições simples tomam uma tarde inteira. Clientes pedem ajustes no último minuto. O escritório fatura menos porque você gasta tempo demais com papel.\n\n**IA para advogados** não substitui seu julgamento — elimina o trabalho braçal de criar documentos do zero.\n\n## Geração automática de contratos e petições\n\nFerramentas criam documentos jurídicos completos a partir de um questionário simples.\n\n### Como funciona na prática:\n\n| O que o cliente preenche | O que a IA faz | O que você recebe |\n|--------------------------|----------------|-------------------|\n| Nome, CPF, valor, prazo | Seleciona cláusulas corretas | Contrato .docx pronto |\n| Tipo de ação, partes, fatos | Estrutura petição padrão | Petição para revisar |\n| Dados do imóvel, locatário | Gera contrato de locação | Documento completo |\n\n**Ferramentas:** **JusDocs** ou **Docassemble**. Você só revisa antes de enviar.\n\n> **Exemplo real:** Um escritório de direito imobiliário reduziu de **2 horas para 15 minutos** a criação de contratos de locação.\n\n> ---\n> **🚀 Quer automatizar a geração de contratos do seu escritório?** Teste grátis por 14 dias. [Comece agora](#)\n> ---\n\n## Análise e revisão de documentos com IA\n\nLer contratos de 50 páginas procurando cláusulas específicas toma tempo. IA faz isso em segundos.\n\n### O que a IA identifica:\n\n- **Cláusulas de risco** — multas, prazos curtos, juros abusivos\n- **Inconsistências** — dados conflitantes entre cláusulas\n- **Omissões** — itens importantes que não foram incluídos\n- **Jurisprudência** — decisões recentes que afetam o caso\n\n> **Dica prática:** Use IA para revisar contratos antes de enviar ao cliente. Reduza o risco de erros em **90%**.\n\n## Checklist para automatizar seu escritório\n\n- [ ] Configure geração automática de contratos com JusDocs ou Docassemble\n- [ ] Use IA para revisar cláusulas de risco e inconsistências\n- [ ] Implemente pesquisa de jurisprudência automatizada\n- [ ] Monitore a redução de tempo gasto em documentos no primeiro mês`.split('\\n').map((l,i)=>{
  if(l.startsWith('## '))return<h2 key={i} className="text-2xl font-bold mt-10 mb-4 text-white">{l.slice(3)}</h2>;
  if(l.startsWith('### '))return<h3 key={i} className="text-xl font-semibold mt-8 mb-3 text-white">{l.slice(4)}</h3>;
  if(l.startsWith('|'))return<p key={i} className="font-mono text-xs text-slate-400 my-1">{l}</p>;
  if(l.startsWith('- [ ]'))return<p key={i} className="flex items-center gap-2 text-slate-300 my-1"><input type="checkbox" className="w-4 h-4 rounded accent-cyan-500" readOnly/>{l.slice(5)}</p>;
  if(l.startsWith('[')){const m=l.match(/\[(.+?)\]\((.+?)\)/);if(m)return<p key={i} className="my-2"><a href={m[2]} target="_blank" className="text-cyan-400 underline">{m[1]}</a></p>}
  if(!l.trim())return<br key={i}/>;return<p key={i} className="text-slate-300 leading-relaxed mb-2">{l}</p>;});
return(<div className="min-h-screen bg-[#0a0a0f]">
  <div className="border-b border-white/[0.04]"><div className="max-w-3xl mx-auto px-6 py-16">
    <Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-cyan-400 text-sm mb-6">← Voltar</Link>
    <span className="inline-block text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-400 font-medium uppercase tracking-wider mb-4">IA</span>
    <h1 className="text-4xl font-bold leading-tight mb-4 text-white">IA para Advogados: Automatize Documentos Juridicos</h1>
    <div className="flex items-center gap-5 text-sm text-slate-500"><span>2026-05-16</span><span>•</span><span>3 min</span></div>
  </div></div>
  <article className="max-w-3xl mx-auto px-6 py-12"><div className="prose prose-invert max-w-none">{content}</div></article>
</div>);}