import{Metadata}from'next';import Link from'next/link';
export const metadata:Metadata={title:'IA para Eletricistas: Orcamentos e Agendamento - Automacao IA'};
export default function Page(){const content=`# Cliente liga, você vai até o local, faz orçamento e ele diz "vou ver e te aviso"\n\n70% não te avisa. Você perdeu 1h30 de deslocamento que não vai receber. Tomada queimada, disjuntor caiu, fio solto — cliente não sabe descrever.\n\n**IA para eletricistas** resolve orçamento e agendamento sem você sair de casa.\n\n## Orçamento automático com diagnóstico remoto\n\nCliente descreve o problema. IA calcula o serviço e o valor sem deslocamento.\n\n### Como funciona na prática:\n\n| Cliente descreve | IA pergunta | Orçamento gerado |\n|------------------|-------------|------------------|\n| "Tomada do quarto parou" | "Quantas tomadas? Caiu disjuntor?" | Troca simples: R$ 110 |\n| "Chuveiro não esquenta" | "Marca? Quantos anos? Fez barulho?" | Troca resistência: R$ 150 |\n| "Curto no quadro geral" | "Desligou geral? Cheiro de queimado?" | Visita técnica: R$ 80 + serviço |\n\n**Ferramentas:** **Orçamento Fácil** ou **Zapier** com IA. Cliente responde, IA calcula, envia PDF por WhatsApp.\n\n> **Exemplo real:** Um eletricista em SP usava orçamento remoto. Antes, ele perdia **3 horas por dia** em visitas que não viravam serviço. Depois, só ia quando o cliente já tinha aprovado o orçamento. A taxa de conversão **subiu de 30% para 80%**.\n\n---\n\n> **🚀 Quer automatizar os orçamentos da sua elétrica?** Teste grátis por 14 dias. [Comece agora](#)\n\n---\n\n## Agendamento inteligente que otimiza rotas\n\nCliente quer marcar, você perde tempo indo e voltando. IA organiza a rota ideal.\n\n### Como funciona:\n\n- Cliente agenda online ou por WhatsApp\n- IA agrupa serviços por região\n- Sugere rota otimizada para o dia\n- Envia confirmação com horário\n\n## Gestão de serviços que nunca perde cliente\n\nCliente ligou, fez orçamento, sumiu. IA lembra e recupera.\n\n**Alertas automáticos:**\n- **24h:** Cliente não respondeu — enviar lembrete\n- **7 dias:** Cliente não fechou — oferta especial\n- **30 dias:** Cliente antigo — pedir avaliação\n- **90 dias:** Cliente inativo — campanha de reativação\n\n## Checklist para crescer como eletricista\n\n- [ ] Configure orçamento automático por WhatsApp\n- [ ] Ative agendamento com rota otimizada\n- [ ] Implemente gestão de clientes com lembretes\n- [ ] Monitore taxa de conversão de orçamentos`.split('\\n').map((l,i)=>{
  if(l.startsWith('## '))return<h2 key={i} className="text-2xl font-bold mt-10 mb-4 text-white">{l.slice(3)}</h2>;
  if(l.startsWith('### '))return<h3 key={i} className="text-xl font-semibold mt-8 mb-3 text-white">{l.slice(4)}</h3>;
  if(l.startsWith('|'))return<p key={i} className="font-mono text-xs text-slate-400 my-1">{l}</p>;
  if(l.startsWith('- [ ]'))return<p key={i} className="flex items-center gap-2 text-slate-300 my-1"><input type="checkbox" className="w-4 h-4 rounded accent-cyan-500" readOnly/>{l.slice(5)}</p>;
  if(l.startsWith('[')){const m=l.match(/\[(.+?)\]\((.+?)\)/);if(m)return<p key={i} className="my-2"><a href={m[2]} target="_blank" className="text-cyan-400 underline">{m[1]}</a></p>}
  if(!l.trim())return<br key={i}/>;return<p key={i} className="text-slate-300 leading-relaxed mb-2">{l}</p>;});
return(<div className="min-h-screen bg-[#0a0a0f]">
  <div className="border-b border-white/[0.04]"><div className="max-w-3xl mx-auto px-6 py-16">
    <Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-cyan-400 text-sm mb-6">\u2190 Voltar</Link>
    <span className="inline-block text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-400 font-medium uppercase tracking-wider mb-4">IA</span>
    <h1 className="text-4xl font-bold leading-tight mb-4 text-white">IA para Eletricistas: Orcamentos e Agendamento</h1>
    <div className="flex items-center gap-5 text-sm text-slate-500"><span>2026-05-16</span><span>\u2022</span><span>3 min</span></div>
  </div></div>
  <article className="max-w-3xl mx-auto px-6 py-12"><div className="prose prose-invert max-w-none">{content}</div></article>
</div>);}