import{Metadata}from'next';import Link from'next/link';
export const metadata:Metadata={title:'IA na Gestao de Bares e Restaurantes - Automacao IA'};
export default function Page(){const content=`# Seu bar está cheio numa sexta e o sistema não acompanha\n\nGarçom anota o pedido, leva a bebida errada. Cliente reclama. 3 pessoas esperam para pagar. 2 pedidos na cozinha atrasaram porque o insumo acabou.\n\n**IA na gestão de bares e restaurantes** resolve esses gargalos sem trocar todo o sistema.\n\n## Cardápio inteligente com preços que se adaptam\n\nEm vez de preço fixo, o cardápio se adapta ao horário, demanda e estoque.\n\n### Como funciona na prática:\n\n| Horário | O que a IA faz | Resultado |\n|---------|----------------|-----------|\n| Happy hour (18h-20h) | Destaca petiscos + cerveja | Combo com desconto |\n| Jantar (20h-23h) | Sugere pratos executivos | Ticket médio maior |\n| Estoque alto de insumo | Aplica desconto automático | Desperdício cai 40% |\n\n**Ferramentas:** Cardápio digital com QR Code + IA integrada. Cliente abre, vê o que a IA sugere, pede.\n\n> **Exemplo real:** Um bar em Curitiba implementou cardápio inteligente. Próximo ao vencimento de insumos, a IA aplicava desconto automático e destacava o prato. O desperdício **caiu 40% em 2 meses**.\n\n---\n\n> **🚀 Quer automatizar a gestão do seu bar ou restaurante?** Teste grátis por 14 dias. [Comece agora](#)\n\n---\n\n## Controle de estoque que prevê a demanda\n\nFaltar cerveja no sábado é venda perdida. Ter insumo parado é dinheiro parado. IA calcula o ponto ideal de reposição.\n\n### O que a IA considera:\n\n- **Histórico de vendas** por dia da semana\n- **Sazonalidade** (feriado, fim de semana, evento)\n- **Prazo do fornecedor** para entrega\n- **Margem de segurança** de 15%\n\n## Gestão de pedidos que acelera o serviço\n\nPedido anotado errado, bebida errada, cliente insatisfeito. IA elimina o erro humano.\n\n**Como funciona:**\n- Garçom usa tablet ou comanda digital\n- Pedido vai direto para cozinha e bar\n- IA prioriza pedidos por tempo de preparo\n- Cliente recebe notificação quando fica pronto\n\n## Checklist para modernizar seu bar\n\n- [ ] Configure cardápio digital com IA\n- [ ] Ative controle de estoque inteligente\n- [ ] Implemente gestão de pedidos digital\n- [ ] Monitore desperdício semanalmente`.split('\\n').map((l,i)=>{
  if(l.startsWith('## '))return<h2 key={i} className="text-2xl font-bold mt-10 mb-4 text-white">{l.slice(3)}</h2>;
  if(l.startsWith('### '))return<h3 key={i} className="text-xl font-semibold mt-8 mb-3 text-white">{l.slice(4)}</h3>;
  if(l.startsWith('|'))return<p key={i} className="font-mono text-xs text-slate-400 my-1">{l}</p>;
  if(l.startsWith('- [ ]'))return<p key={i} className="flex items-center gap-2 text-slate-300 my-1"><input type="checkbox" className="w-4 h-4 rounded accent-cyan-500" readOnly/>{l.slice(5)}</p>;
  if(l.startsWith('[')){const m=l.match(/\[(.+?)\]\((.+?)\)/);if(m)return<p key={i} className="my-2"><a href={m[2]} target="_blank" className="text-cyan-400 underline">{m[1]}</a></p>}
  if(!l.trim())return<br key={i}/>;return<p key={i} className="text-slate-300 leading-relaxed mb-2">{l}</p>;});
return(<div className="min-h-screen bg-[#0a0a0f]">
  <div className="border-b border-white/[0.04]"><div className="max-w-3xl mx-auto px-6 py-16">
    <Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-cyan-400 text-sm mb-6">\u2190 Voltar</Link>
    <span className="inline-block text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-400 font-medium uppercase tracking-wider mb-4">IA</span>
    <h1 className="text-4xl font-bold leading-tight mb-4 text-white">IA na Gestao de Bares e Restaurantes</h1>
    <div className="flex items-center gap-5 text-sm text-slate-500"><span>2026-05-16</span><span>\u2022</span><span>3 min</span></div>
  </div></div>
  <article className="max-w-3xl mx-auto px-6 py-12"><div className="prose prose-invert max-w-none">{content}</div></article>
</div>);}