import{Metadata}from'next';import Link from'next/link';
export const metadata:Metadata={title:'Como Automatizar Email Marketing com IA - Automacao IA'};
export default function Page(){const content=`# Você tem uma lista de e-mails, mas não sabe o que enviar\n\nEscrever sequência de e-mails toda semana consome horas. Ou você paga caro por ferramentas que prometem resultados e entregam pouco.\n\n**Email marketing** ainda tem o maior retorno entre canais digitais. O problema é executar. Com IA e automação, você cria campanhas que disparam sozinhas com conteúdo personalizado.\n\n## O que você precisa para começar\n\n| Ferramenta | Função | Preço |\n|------------|--------|-------|\n| **Make** | Orquestrador da automação | Grátis / 1.000 operações |\n| **DeepSeek** | IA para gerar os textos | Grátis (500 req/dia) |\n| **Mailchimp** | Disparo dos e-mails | Grátis / 500 contatos |\n| **Google Sheets** | Base de dados dos contatos | Grátis |\n\nTodas têm plano gratuito. Você testa sem gastar nada.\n\n## Passo a passo: do Google Sheets ao e-mail personalizado\n\n### 1. Prepare sua base de contatos\n\nCrie uma planilha no Google Sheets com colunas simples:\n\n| Nome | E-mail | Segmento | Última compra |\n|------|--------|----------|---------------|\n| João | joao@email.com | Premium | 15/01 |\n| Maria | maria@email.com | Básico | 20/12 |\n\n### 2. Configure o fluxo no Make\n\nCrie um cenário com 3 módulos:\n\n1. **Trigger** — Novo contato no Sheets\n2. **IA** — DeepSeek gera e-mail personalizado\n3. **Ação** — Mailchimp dispara o e-mail\n\n---\n\n> **🚀 Automatize seu email marketing em 30 minutos.** Teste grátis com template pronto. [Comece agora](#)\n\n---\n\n### 3. Personalize com dados reais\n\nA IA recebe o nome, segmento e última compra. Gera um e-mail único para cada contato.\n\n**Exemplo de prompt:**\n> "Escreva um e-mail para {Nome}, cliente {Segmento}, que comprou em {Última compra}. Sugira produtos complementares."\n\n## Tipos de campanha que rodam sozinhas\n\n- **Boas-vindas:** Novo assinante recebe 3 e-mails automáticos\n- **Carrinho abandonado:** Lembrete após 1h, 24h e 72h\n- **Reativação:** Cliente inativo há 90 dias recebe oferta especial\n- **Pós-venda:** Confirmação + pesquisa de satisfação\n\n## Checklist para sua primeira automação\n\n- [ ] Configure planilha com dados dos contatos\n- [ ] Crie conta no Make e Mailchimp\n- [ ] Monte o fluxo: Sheets → IA → Disparo\n- [ ] Teste com 5 contatos antes de escalar`.split('\\n').map((l,i)=>{
  if(l.startsWith('## '))return<h2 key={i} className="text-2xl font-bold mt-10 mb-4 text-white">{l.slice(3)}</h2>;
  if(l.startsWith('### '))return<h3 key={i} className="text-xl font-semibold mt-8 mb-3 text-white">{l.slice(4)}</h3>;
  if(l.startsWith('|'))return<p key={i} className="font-mono text-xs text-slate-400 my-1">{l}</p>;
  if(l.startsWith('- [ ]'))return<p key={i} className="flex items-center gap-2 text-slate-300 my-1"><input type="checkbox" className="w-4 h-4 rounded accent-cyan-500" readOnly/>{l.slice(5)}</p>;
  if(l.startsWith('[')){const m=l.match(/\[(.+?)\]\((.+?)\)/);if(m)return<p key={i} className="my-2"><a href={m[2]} target="_blank" className="text-cyan-400 underline">{m[1]}</a></p>}
  if(!l.trim())return<br key={i}/>;return<p key={i} className="text-slate-300 leading-relaxed mb-2">{l}</p>;});
return(<div className="min-h-screen bg-[#0a0a0f]">
  <div className="border-b border-white/[0.04]"><div className="max-w-3xl mx-auto px-6 py-16">
    <Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-cyan-400 text-sm mb-6">\u2190 Voltar</Link>
    <span className="inline-block text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-400 font-medium uppercase tracking-wider mb-4">IA</span>
    <h1 className="text-4xl font-bold leading-tight mb-4 text-white">Como Automatizar Email Marketing com IA</h1>
    <div className="flex items-center gap-5 text-sm text-slate-500"><span>2026-05-16</span><span>\u2022</span><span>3 min</span></div>
  </div></div>
  <article className="max-w-3xl mx-auto px-6 py-12"><div className="prose prose-invert max-w-none">{content}</div></article>
</div>);}