import{Metadata}from'next';import Link from'next/link';
export const metadata:Metadata={title:'IA no Atendimento Medico: Chatbots e Triagem - Automacao IA'};
export default function Page(){const content=`# Você perde consultas porque paciente desiste de esperar no telefone\n\nSeu consultório recebe 50 ligações por dia. Paciente quer saber se o sintoma é grave. Outro pergunta se tem horário. A recepcionista passa o dia no telefone enquanto a sala de espera lota.\n\nNo fim do dia, **3 consultas foram perdidas**. O paciente desistiu de esperar.\n\n> IA no atendimento médico em 2026 não substitui seu diagnóstico. Ela organiza o fluxo para você atender quem realmente precisa, na hora certa.\n\n## Chatbot de triagem: paciente descreve, IA classifica\n\nPaciente chega com dor de cabeça. É tensão ou algo sério? Um chatbot faz a primeira avaliação antes de qualquer consulta.\n\n### Como funciona na prática:\n\n| Ação | O que o robô faz | Resultado |\n|------|------------------|-----------|\n| Paciente descreve sintomas | Faz perguntas de acompanhamento | Classifica gravidade |\n| Dor forte no peito | Encaminha para emergência | Paciente vai direto para UPA |\n| Dor de cabeça leve | Agenda consulta de rotina | Libera a recepcionista |\n\n> **Exemplo real:** Uma clínica em Belo Horizonte implantou triagem por chatbot. O número de pacientes que iam ao pronto-socorro sem necessidade **caiu 40%**. Quem realmente precisava de atendimento urgente foi priorizado.\n\n---\n\n> **🚀 Automatize a triagem do seu consultório.** Teste grátis por 14 dias e veja quantas consultas você recupera. [Comece agora](#)\n\n---\n\n## Check-in digital: zero papelada na recepção\n\nPaciente chega, escaneia QR code na porta. Em 30 segundos, preenche ficha, confirma dados e libera senha.\n\n**Benefícios:**\n- Fila virtual com aviso por WhatsApp\n- Documentos enviados antes da consulta\n- Prontuário atualizado automaticamente\n- Recepcionista livre para casos complexos\n\n## Agendamento inteligente\n\nO sistema aprende os horários de maior procura. Sugere slots ideais para cada especialidade.\n\n**Resultado:** Redução de **25%** em faltas. Paciente recebe lembrete automático 24h antes.\n\n## Checklist para digitalizar seu consultório\n\n- [ ] Configure um chatbot de triagem no WhatsApp\n- [ ] Implemente QR code para check-in digital\n- [ ] Ative lembretes automáticos de consulta\n- [ ] Treine a equipe para focar em casos complexos`.split('\\n').map((l,i)=>{
  if(l.startsWith('## '))return<h2 key={i} className="text-2xl font-bold mt-10 mb-4 text-white">{l.slice(3)}</h2>;
  if(l.startsWith('### '))return<h3 key={i} className="text-xl font-semibold mt-8 mb-3 text-white">{l.slice(4)}</h3>;
  if(l.startsWith('|'))return<p key={i} className="font-mono text-xs text-slate-400 my-1">{l}</p>;
  if(l.startsWith('- [ ]'))return<p key={i} className="flex items-center gap-2 text-slate-300 my-1"><input type="checkbox" className="w-4 h-4 rounded accent-cyan-500" readOnly/>{l.slice(5)}</p>;
  if(l.startsWith('[')){const m=l.match(/\[(.+?)\]\((.+?)\)/);if(m)return<p key={i} className="my-2"><a href={m[2]} target="_blank" className="text-cyan-400 underline">{m[1]}</a></p>}
  if(!l.trim())return<br key={i}/>;return<p key={i} className="text-slate-300 leading-relaxed mb-2">{l}</p>;});
return(<div className="min-h-screen bg-[#0a0a0f]">
  <div className="border-b border-white/[0.04]"><div className="max-w-3xl mx-auto px-6 py-16">
    <Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-cyan-400 text-sm mb-6">\u2190 Voltar</Link>
    <span className="inline-block text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-400 font-medium uppercase tracking-wider mb-4">IA</span>
    <h1 className="text-4xl font-bold leading-tight mb-4 text-white">IA no Atendimento Medico: Chatbots e Triagem</h1>
    <div className="flex items-center gap-5 text-sm text-slate-500"><span>2026-05-16</span><span>\u2022</span><span>3 min</span></div>
  </div></div>
  <article className="max-w-3xl mx-auto px-6 py-12"><div className="prose prose-invert max-w-none">{content}</div></article>
</div>);}