import{Metadata}from'next';import Link from'next/link';
export const metadata:Metadata={title:'Como Usar IA para Analisar Dados da Sua Empresa - Automacao IA'};
export default function Page(){const content=`# Você tem planilhas cheias de dados, mas não sabe o que eles significam\n\nVendas, estoque, clientes, financeiro. Você acumula números, mas poucos geram decisão. Dados parados não servem para nada.\n\nIA transforma números brutos em insights acionáveis em segundos. Sem ser analista de dados. Sem fórmulas complexas.\n\n## O que você precisa para começar\n\n| Ferramenta | Função | Preço |\n|------------|--------|-------|\n| **Google Sheets** | Onde seus dados vivem | Grátis |\n| **Make** | Orquestrador da análise | Grátis (1.000 op/mês) |\n| **DeepSeek** | IA para interpretar dados | Grátis (500 req/dia) |\n| **Gmail** | Entrega do relatório | Grátis |\n\nTudo gratuito. Você testa sem gastar nada.\n\n## Passo a passo: dados brutos → relatório pronto\n\n### 1. Prepare seus dados\n\nOrganize em formato tabular. Primeira linha com cabeçalhos claros. Sem células mescladas.\n\n| Mês | Vendas | Custos | Clientes novos | Ticket médio |\n|-----|--------|--------|----------------|--------------|\n| Jan | 15.000 | 8.000 | 45 | 333 |\n| Fev | 18.000 | 8.500 | 52 | 346 |\n| Mar | 14.500 | 8.200 | 38 | 382 |\n\n### 2. Configure o fluxo no Make\n\nCrie um cenário com 4 módulos:\n\n1. **Trigger:** Agendamento (toda segunda às 9h)\n2. **Leitura:** Busca dados da planilha\n3. **IA:** DeepSeek analisa e gera relatório\n4. **Entrega:** Envia por e-mail\n\n---\n\n> **🚀 Quer o template pronto?** Baixe grátis e configure em 30 minutos. [Comece agora](#)\n\n---\n\n### 3. O que a IA analisa\n\nA IA recebe os dados e responde perguntas específicas. Você define o que quer saber.\n\n**Exemplos de análise:**\n- "Qual mês teve maior crescimento?"\n- "Ticket médio está subindo ou caindo?"\n- "Custos cresceram mais que vendas?"\n- "Quais clientes estão prestes a cancelar?"\n\n## 3 relatórios para automatizar esta semana\n\n- **Relatório de vendas:** Resumo semanal enviado toda segunda\n- **Análise de estoque:** Produtos parados há mais de 60 dias\n- **Saúde financeira:** Margem, inadimplência e fluxo de caixa\n\n## Checklist para sua primeira análise\n\n- [ ] Organize dados em formato tabular\n- [ ] Crie conta no Make e conecte ao Sheets\n- [ ] Defina 3 perguntas que quer responder\n- [ ] Agende relatório semanal automático`.split('\\n').map((l,i)=>{
  if(l.startsWith('## '))return<h2 key={i} className="text-2xl font-bold mt-10 mb-4 text-white">{l.slice(3)}</h2>;
  if(l.startsWith('### '))return<h3 key={i} className="text-xl font-semibold mt-8 mb-3 text-white">{l.slice(4)}</h3>;
  if(l.startsWith('|'))return<p key={i} className="font-mono text-xs text-slate-400 my-1">{l}</p>;
  if(l.startsWith('- [ ]'))return<p key={i} className="flex items-center gap-2 text-slate-300 my-1"><input type="checkbox" className="w-4 h-4 rounded accent-cyan-500" readOnly/>{l.slice(5)}</p>;
  if(l.startsWith('[')){const m=l.match(/\[(.+?)\]\((.+?)\)/);if(m)return<p key={i} className="my-2"><a href={m[2]} target="_blank" className="text-cyan-400 underline">{m[1]}</a></p>}
  if(!l.trim())return<br key={i}/>;return<p key={i} className="text-slate-300 leading-relaxed mb-2">{l}</p>;});
return(<div className="min-h-screen bg-[#0a0a0f]">
  <div className="border-b border-white/[0.04]"><div className="max-w-3xl mx-auto px-6 py-16">
    <Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-cyan-400 text-sm mb-6">\u2190 Voltar</Link>
    <span className="inline-block text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-400 font-medium uppercase tracking-wider mb-4">IA</span>
    <h1 className="text-4xl font-bold leading-tight mb-4 text-white">Como Usar IA para Analisar Dados da Sua Empresa</h1>
    <div className="flex items-center gap-5 text-sm text-slate-500"><span>2026-05-16</span><span>\u2022</span><span>3 min</span></div>
  </div></div>
  <article className="max-w-3xl mx-auto px-6 py-12"><div className="prose prose-invert max-w-none">{content}</div></article>
</div>);}