import{Metadata}from'next';import Link from'next/link';
export const metadata:Metadata={title:'10 Melhores Prompts do ChatGPT para Pequenos Negocios - Automacao IA'};
export default function Page(){const content=`# Você abre o ChatGPT, digita "me ajuda com meu negócio" e recebe um textão genérico\n\nTodo mundo tem acesso ao ChatGPT, mas poucos sabem usar direito. O segredo está no **prompt**. Um prompt bem escrito entrega resultado pronto. Um prompt genérico dá resposta genérica.\n\nEstes 10 prompts são testados em negócios reais e funcionam.\n\n## Como usar cada prompt\n\nCada prompt resolve um problema específico. Cole, substitua o que está entre colchetes e pronto.\n\n### Estrutura de cada prompt:\n\n| Parte | O que fazer |\n|-------|-------------|\n| [tipo de produto] | Substitua pelo seu produto |\n| [público-alvo] | Descreva seu cliente ideal |\n| [problema] | Seja específico |\n\n## Os 10 prompts que funcionam\n\n### 1. Criação de nome para produto\n\n\`\`\`\nCrie 10 nomes para um [tipo de produto] voltado para [público-alvo].\nRequisitos: fácil de pronunciar, máximo 2 sílabas, domínio .com.br disponível.\nExplique o significado de cada nome.\n\`\`\`\n\n**Resultado:** Nomes prontos para registrar. Economiza horas de brainstorming.\n\n### 2. Descrição de produto para e-commerce\n\n\`\`\`\nEscreva uma descrição de produto para [nome do produto].\nTamanho: 100 palavras. Tom: persuasivo mas honesto.\nInclua: 3 benefícios principais, 2 provas sociais, 1 CTA.\n\`\`\`\n\n**Resultado:** Descrição pronta para publicar. Aumenta conversão.\n\n> ---\n> **🚀 Quer prompts prontos para seu negócio?** Teste grátis por 14 dias. [Comece agora](#)\n> ---\n\n### 3. Roteiro de vídeo curto (Reels/TikTok)\n\n\`\`\`\nCrie um roteiro de 60 segundos sobre [tema].\nGancho nos primeiros 3 segundos. Tom [informal/profissional].\nInclua: problema, solução, CTA no final.\n\`\`\`\n\n**Resultado:** Roteiro pronto para gravar. Aumenta retenção.\n\n### 4. E-mail de follow-up para leads frios\n\n\`\`\`\nEscreva um e-mail de follow-up para um lead que não respondeu há 7 dias.\nProduto: [nome]. Problema que resolve: [problema].\nTom: útil, não insistente. Máximo 80 palavras.\n\`\`\`\n\n**Resultado:** E-mail que recupera leads. Aumenta conversão em 3x.\n\n### 5. Análise de concorrente\n\n\`\`\`\nAnalise o concorrente [nome do concorrente].\nPontos fortes, pontos fracos, estratégia de preço, público-alvo.\nSugira 3 ações para se diferenciar.\n\`\`\`\n\n**Resultado:** Estratégia competitiva clara em minutos.\n\n## Checklist para usar prompts de IA\n\n- [ ] Substitua sempre os colchetes por informações específicas do seu negócio\n- [ ] Teste cada prompt 3 vezes com variações no tom e no público\n- [ ] Salve os prompts que funcionam como templates reutilizáveis\n- [ ] Monitore a qualidade das respostas e ajuste os prompts conforme necessário`.split('\\n').map((l,i)=>{
  if(l.startsWith('## '))return<h2 key={i} className="text-2xl font-bold mt-10 mb-4 text-white">{l.slice(3)}</h2>;
  if(l.startsWith('### '))return<h3 key={i} className="text-xl font-semibold mt-8 mb-3 text-white">{l.slice(4)}</h3>;
  if(l.startsWith('|'))return<p key={i} className="font-mono text-xs text-slate-400 my-1">{l}</p>;
  if(l.startsWith('- [ ]'))return<p key={i} className="flex items-center gap-2 text-slate-300 my-1"><input type="checkbox" className="w-4 h-4 rounded accent-cyan-500" readOnly/>{l.slice(5)}</p>;
  if(l.startsWith('[')){const m=l.match(/\[(.+?)\]\((.+?)\)/);if(m)return<p key={i} className="my-2"><a href={m[2]} target="_blank" className="text-cyan-400 underline">{m[1]}</a></p>}
  if(!l.trim())return<br key={i}/>;return<p key={i} className="text-slate-300 leading-relaxed mb-2">{l}</p>;});
return(<div className="min-h-screen bg-[#0a0a0f]">
  <div className="border-b border-white/[0.04]"><div className="max-w-3xl mx-auto px-6 py-16">
    <Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-cyan-400 text-sm mb-6">← Voltar</Link>
    <span className="inline-block text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-400 font-medium uppercase tracking-wider mb-4">IA</span>
    <h1 className="text-4xl font-bold leading-tight mb-4 text-white">10 Melhores Prompts do ChatGPT para Pequenos Negocios</h1>
    <div className="flex items-center gap-5 text-sm text-slate-500"><span>2026-05-16</span><span>•</span><span>3 min</span></div>
  </div></div>
  <article className="max-w-3xl mx-auto px-6 py-12"><div className="prose prose-invert max-w-none">{content}</div></article>
</div>);}