import{Metadata}from'next';import Link from'next/link';
export const metadata:Metadata={title:'IA para Escritores: Ferramentas que Potencializam a Criatividade - Automacao IA'};
export default function Page(){const content=`# Você senta para escrever, mas a tela fica em branco por uma hora\n\nDigita uma frase, apaga. Digita outra, apaga. O prazo está chegando e a criatividade simplesmente não vem.\n\nO bloqueio criativo não é falta de talento. É falta de estímulo. **IA para escritores** não substitui sua voz autoral. Ela quebra o gelo e acelera a revisão.\n\n## Geração de ideias que quebra o bloqueio\n\nA pior parte de escrever é a primeira frase. IA resolve isso com prompts direcionados.\n\n### Como funciona na prática:\n\n| O que você quer | Prompt para IA | Resultado |\n|-----------------|----------------|-----------|\n| Ideias de contos | "10 ideias de contos sobre IA e memória humana" | 10 ideias em 2 frases cada |\n| Abertura de artigo | "5 aberturas para artigo sobre automação" | Pergunta, dado, cena, citação, declaração |\n| Personagens | "3 perfis de personagens para romance policial" | Nome, idade, profissão, conflito |\n\n**Ferramentas:** **ChatGPT**, **Claude** ou **Sudowrite**. O segredo é o prompt certo.\n\n**Prompt que funciona para qualquer gênero:**\n\n> "Preciso de 5 aberturas diferentes para um artigo sobre [tema]. A primeira frase deve prender a atenção. Opções: pergunta provocativa, dado chocante, cena descritiva."\n\n---\n\n> **🚀 Quer uma biblioteca de prompts prontos para escritores?** Baixe grátis. [Baixar agora](#)\n\n---\n\n## Revisão que não perde sua voz\n\nIA revisa gramática, estilo e fluidez. Mas mantém seu tom e suas escolhas criativas.\n\n### O que a IA revisa:\n\n- **Gramática:** Ortografia, concordância, pontuação\n- **Estilo:** Frases longas, repetições, clichês\n- **Fluidez:** Transições entre parágrafos\n- **Tom:** Formal, informal, técnico, poético\n\n## Estruturação de textos longos\n\nArtigos, capítulos, roteiros. IA organiza o conteúdo em seções lógicas.\n\n**Como funciona:**\n- Você descreve o tema e os pontos principais\n- IA sugere estrutura com títulos e subtítulos\n- Você aprova e começa a escrever cada seção\n\n## Checklist para escrever com IA\n\n- [ ] Use prompts para gerar 5 aberturas diferentes\n- [ ] Escolha a melhor e peça IA para expandir\n- [ ] Revise gramática e estilo com IA\n- [ ] Ajuste o tom final com sua voz autoral`.split('\\n').map((l,i)=>{
  if(l.startsWith('## '))return<h2 key={i} className="text-2xl font-bold mt-10 mb-4 text-white">{l.slice(3)}</h2>;
  if(l.startsWith('### '))return<h3 key={i} className="text-xl font-semibold mt-8 mb-3 text-white">{l.slice(4)}</h3>;
  if(l.startsWith('|'))return<p key={i} className="font-mono text-xs text-slate-400 my-1">{l}</p>;
  if(l.startsWith('- [ ]'))return<p key={i} className="flex items-center gap-2 text-slate-300 my-1"><input type="checkbox" className="w-4 h-4 rounded accent-cyan-500" readOnly/>{l.slice(5)}</p>;
  if(l.startsWith('[')){const m=l.match(/\[(.+?)\]\((.+?)\)/);if(m)return<p key={i} className="my-2"><a href={m[2]} target="_blank" className="text-cyan-400 underline">{m[1]}</a></p>}
  if(!l.trim())return<br key={i}/>;return<p key={i} className="text-slate-300 leading-relaxed mb-2">{l}</p>;});
return(<div className="min-h-screen bg-[#0a0a0f]">
  <div className="border-b border-white/[0.04]"><div className="max-w-3xl mx-auto px-6 py-16">
    <Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-cyan-400 text-sm mb-6">\u2190 Voltar</Link>
    <span className="inline-block text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-400 font-medium uppercase tracking-wider mb-4">IA</span>
    <h1 className="text-4xl font-bold leading-tight mb-4 text-white">IA para Escritores: Ferramentas que Potencializam a Criatividade</h1>
    <div className="flex items-center gap-5 text-sm text-slate-500"><span>2026-05-16</span><span>\u2022</span><span>3 min</span></div>
  </div></div>
  <article className="max-w-3xl mx-auto px-6 py-12"><div className="prose prose-invert max-w-none">{content}</div></article>
</div>);}