import{Metadata}from'next';import Link from'next/link';
export const metadata:Metadata={title:'IA para Chefs: Cardapios, Receitas e Precificacao - Automacao IA'};
export default function Page(){const content=`# Você passa horas criando o cardápio e descobre que 3 pratos têm margem negativa\n\nCalcula custo manualmente. Um ingrediente não tem fornecedor. Outro prato é igual ao do concorrente. No fim, mantém o mesmo cardápio de sempre por medo de errar.\n\n**IA para chefs** resolve criação de cardápio, receitas e precificação.\n\n## Criação de cardápio sazonal baseado em dados\n\nCardápio repetido cansa o cliente. IA sugere pratos baseados no que está em alta.\n\n### Como funciona na prática:\n\n| O que a IA analisa | O que sugere | Margem calculada |\n|--------------------|--------------|------------------|\n| Cogumelo shimeji em alta | Risoto de cogumelo com parmesão | Custo R$ 8 / Preço R$ 32 = 75% |\n| Clientes pedem mais opções vegetarianas | Bowl de quinoa com legumes | Custo R$ 6 / Preço R$ 24 = 75% |\n| Ingrediente da estação (abóbora) | Nhoque de abóbora com manteiga | Custo R$ 5 / Preço R$ 22 = 77% |\n\n**Ferramentas:** **Plate IQ** ou **MarketMan**. IA analisa tendências, ingredientes da estação e avaliações dos clientes.\n\n> **Exemplo real:** Um chef em SP usava IA para criar cardápios sazonais. O tempo de criação **caiu de 3 dias para 4 horas**. A margem média **subiu 12 pontos percentuais**.\n\n---\n\n> **🚀 Quer automatizar a criação de cardápios do seu restaurante?** Teste grátis por 14 dias. [Comece agora](#)\n\n---\n\n## Desenvolvimento de receitas com custo calculado\n\nCriar receita nova é chute. IA calcula custo de cada ingrediente e sugere substituições.\n\n### O que a IA faz:\n\n- **Calcula custo** por porção automaticamente\n- **Sugere substituições** para ingredientes caros\n- **Ajusta quantidade** para evitar desperdício\n- **Gera ficha técnica** completa\n\n## Precificação inteligente que garante margem\n\nPreço errado é prejuízo. IA calcula o preço ideal com base no custo e no mercado.\n\n**Como funciona:**\n- Calcula custo total do prato\n- Aplica margem desejada (70-80%)\n- Compara com preço de concorrentes\n- Sugere preço final competitivo\n\n## Checklist para otimizar seu cardápio\n\n- [ ] Configure IA para análise de tendências\n- [ ] Ative cálculo automático de custo por receita\n- [ ] Implemente precificação inteligente\n- [ ] Renove cardápio a cada estação`.split('\\n').map((l,i)=>{
  if(l.startsWith('## '))return<h2 key={i} className="text-2xl font-bold mt-10 mb-4 text-white">{l.slice(3)}</h2>;
  if(l.startsWith('### '))return<h3 key={i} className="text-xl font-semibold mt-8 mb-3 text-white">{l.slice(4)}</h3>;
  if(l.startsWith('|'))return<p key={i} className="font-mono text-xs text-slate-400 my-1">{l}</p>;
  if(l.startsWith('- [ ]'))return<p key={i} className="flex items-center gap-2 text-slate-300 my-1"><input type="checkbox" className="w-4 h-4 rounded accent-cyan-500" readOnly/>{l.slice(5)}</p>;
  if(l.startsWith('[')){const m=l.match(/\[(.+?)\]\((.+?)\)/);if(m)return<p key={i} className="my-2"><a href={m[2]} target="_blank" className="text-cyan-400 underline">{m[1]}</a></p>}
  if(!l.trim())return<br key={i}/>;return<p key={i} className="text-slate-300 leading-relaxed mb-2">{l}</p>;});
return(<div className="min-h-screen bg-[#0a0a0f]">
  <div className="border-b border-white/[0.04]"><div className="max-w-3xl mx-auto px-6 py-16">
    <Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-cyan-400 text-sm mb-6">\u2190 Voltar</Link>
    <span className="inline-block text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-400 font-medium uppercase tracking-wider mb-4">IA</span>
    <h1 className="text-4xl font-bold leading-tight mb-4 text-white">IA para Chefs: Cardapios, Receitas e Precificacao</h1>
    <div className="flex items-center gap-5 text-sm text-slate-500"><span>2026-05-16</span><span>\u2022</span><span>3 min</span></div>
  </div></div>
  <article className="max-w-3xl mx-auto px-6 py-12"><div className="prose prose-invert max-w-none">{content}</div></article>
</div>);}