import{Metadata}from'next';import Link from'next/link';
export const metadata:Metadata={title:'IA para Lavanderias: Pedidos e Entregas Automaticos - Automacao IA'};
export default function Page(){const content=`# Cliente liga, você anota no papel e a peça some no processo\n\n"Quero lavar 3 camisas, 2 calças e 1 terno." Você anota. Motoboy busca, cliente não estava em casa. Peças chegam, você separa manualmente, etiqueta. Depois descobre que uma camisa sumiu.\n\nCliente reclama, você não tem registro. No fim do mês, perdeu **3 clientes** por extravio e atraso.\n\n**IA para lavanderias** organiza cada peça, cada pedido e cada entrega sem papel. São 3 áreas que entregam resultado imediato.\n\n## Pedido online que o cliente faz sozinho\n\nCliente quer lavar mas não quer sair de casa. IA gerencia o pedido do início ao fim.\n\n### Como funciona na prática:\n\n| O que o cliente faz | O que a IA processa | Resultado |\n|--------------------|--------------------|-----------|\n| Seleciona itens no app | Calcula preço automático | R$ 47,50 |\n| Escolhe horário de coleta | Agenda na rota do motoboy | Coleta entre 14h-16h |\n| Confirma o pedido | Envia comprovante por WhatsApp | Pedido registrado |\n\n**Ferramentas:** App próprio ou **Make** + **WhatsApp Business API**. Cliente faz tudo sem falar com ninguém.\n\n> **Exemplo real:** Uma lavanderia em Florianópolis implementou pedido online com IA. O volume de pedidos **dobrou em 60 dias**. Os extravios **caíram de 5 para 0** por mês.\n\n> ---\n> **🚀 Quer automatizar os pedidos da sua lavanderia?** Teste grátis por 14 dias. [Comece agora](#)\n> ---\n\n## Rastreamento de peças que elimina extravio\n\nCada peça recebe uma etiqueta digital. Você sabe onde está a qualquer momento.\n\n### Como funciona:\n\n1. **Entrada:** Peça é etiquetada com QR code ou RFID\n2. **Processo:** Cada etapa (lavagem, secagem, passadoria) é registrada\n3. **Saída:** Peça é desvinculada na entrega ao cliente\n4. **Histórico:** Cliente vê o status em tempo real pelo WhatsApp\n\n> **Dica prática:** Use etiquetas térmicas com QR code. Custo de **R$ 0,02 por peça**. Elimina totalmente o extravio.\n\n## Checklist para digitalizar sua lavanderia\n\n- [ ] Configure pedido online via WhatsApp Business API + Make\n- [ ] Implemente etiquetagem digital (QR code ou RFID) para cada peça\n- [ ] Ative notificações automáticas de status para o cliente\n- [ ] Monitore a redução de extravios e reclamações no primeiro mês`.split('\\n').map((l,i)=>{
  if(l.startsWith('## '))return<h2 key={i} className="text-2xl font-bold mt-10 mb-4 text-white">{l.slice(3)}</h2>;
  if(l.startsWith('### '))return<h3 key={i} className="text-xl font-semibold mt-8 mb-3 text-white">{l.slice(4)}</h3>;
  if(l.startsWith('|'))return<p key={i} className="font-mono text-xs text-slate-400 my-1">{l}</p>;
  if(l.startsWith('- [ ]'))return<p key={i} className="flex items-center gap-2 text-slate-300 my-1"><input type="checkbox" className="w-4 h-4 rounded accent-cyan-500" readOnly/>{l.slice(5)}</p>;
  if(l.startsWith('[')){const m=l.match(/\[(.+?)\]\((.+?)\)/);if(m)return<p key={i} className="my-2"><a href={m[2]} target="_blank" className="text-cyan-400 underline">{m[1]}</a></p>}
  if(!l.trim())return<br key={i}/>;return<p key={i} className="text-slate-300 leading-relaxed mb-2">{l}</p>;});
return(<div className="min-h-screen bg-[#0a0a0f]">
  <div className="border-b border-white/[0.04]"><div className="max-w-3xl mx-auto px-6 py-16">
    <Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-cyan-400 text-sm mb-6">← Voltar</Link>
    <span className="inline-block text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-400 font-medium uppercase tracking-wider mb-4">IA</span>
    <h1 className="text-4xl font-bold leading-tight mb-4 text-white">IA para Lavanderias: Pedidos e Entregas Automaticos</h1>
    <div className="flex items-center gap-5 text-sm text-slate-500"><span>2026-05-16</span><span>•</span><span>3 min</span></div>
  </div></div>
  <article className="max-w-3xl mx-auto px-6 py-12"><div className="prose prose-invert max-w-none">{content}</div></article>
</div>);}