import{Metadata}from'next';import Link from'next/link';
export const metadata:Metadata={title:'Como Automatizar RH e Contratacao com IA - Automacao IA'};
export default function Page(){const content=`# Você publica uma vaga e recebe 200 currículos em 24 horas\n\nLer um por um leva dias. Marcar entrevista é um vai-e-vem de e-mails. No fim, você contrata na pressa porque a vaga está aberta há semanas.\n\nAutomatizar RH com IA elimina o gargalo da triagem e acelera a contratação sem perder qualidade. São 3 áreas que entregam resultado imediato.\n\n## Triagem de currículos em horas, não em dias\n\nFerramentas como **TurboHire** e **Manatal** usam IA para ler currículos e classificar candidatos por compatibilidade.\n\n### Como funciona na prática:\n\n| Etapa | O que a IA faz | Resultado |\n|-------|----------------|-----------|\n| Recebe 200 currículos | Varre e pontua cada um | Classifica do melhor ao pior |\n| Filtra por critérios | Formação, experiência, habilidades | Só os 10 melhores vão para o RH |\n| Gera relatório | Resumo de cada candidato | Análise em 2 horas |\n\n> **Exemplo real:** Uma empresa de tecnologia recebia 150 currículos por vaga. Com triagem por IA, reduziu o tempo de análise de **3 dias para 2 horas**. O RH só olhava os 15% melhores classificados.\n\n## Agendamento de entrevista sem e-mail\n\nO vai-e-vem de e-mails para achar um horário comum é um dos maiores desperdícios de tempo no RH.\n\n### Como resolver:\n\n- **Calendly** ou **TidyCal** mostram sua agenda disponível\n- Candidato escolhe o horário que encaixa\n- Confirmação automática com link de videoconferência\n- Lembrete enviado 24h antes\n\n> ---\n> **🚀 Automatize seu processo seletivo em 1 hora.** Teste grátis por 14 dias. [Comece agora](#)\n> ---\n\n## Perguntas frequentes que o robô responde sozinho\n\nCandidatos enviam as mesmas perguntas repetitivas sobre a vaga. IA responde automaticamente sem ocupar o RH.\n\n### O que o chatbot responde:\n\n- **Requisitos:** Formação, experiência, habilidades técnicas\n- **Benefícios:** Salário, vale-refeição, plano de saúde\n- **Processo:** Etapas, prazos, formato das entrevistas\n- **Feedback:** Status da candidatura, resultado final\n\n## Checklist para automatizar seu RH\n\n- [ ] Configure a triagem automática de currículos com IA\n- [ ] Ative o agendamento online de entrevistas (Calendly ou similar)\n- [ ] Crie um chatbot para responder perguntas frequentes sobre a vaga\n- [ ] Monitore o tempo de fechamento de vaga na primeira semana`.split('\\n').map((l,i)=>{
  if(l.startsWith('## '))return<h2 key={i} className="text-2xl font-bold mt-10 mb-4 text-white">{l.slice(3)}</h2>;
  if(l.startsWith('### '))return<h3 key={i} className="text-xl font-semibold mt-8 mb-3 text-white">{l.slice(4)}</h3>;
  if(l.startsWith('|'))return<p key={i} className="font-mono text-xs text-slate-400 my-1">{l}</p>;
  if(l.startsWith('- [ ]'))return<p key={i} className="flex items-center gap-2 text-slate-300 my-1"><input type="checkbox" className="w-4 h-4 rounded accent-cyan-500" readOnly/>{l.slice(5)}</p>;
  if(l.startsWith('[')){const m=l.match(/\[(.+?)\]\((.+?)\)/);if(m)return<p key={i} className="my-2"><a href={m[2]} target="_blank" className="text-cyan-400 underline">{m[1]}</a></p>}
  if(!l.trim())return<br key={i}/>;return<p key={i} className="text-slate-300 leading-relaxed mb-2">{l}</p>;});
return(<div className="min-h-screen bg-[#0a0a0f]">
  <div className="border-b border-white/[0.04]"><div className="max-w-3xl mx-auto px-6 py-16">
    <Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-cyan-400 text-sm mb-6">← Voltar</Link>
    <span className="inline-block text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-400 font-medium uppercase tracking-wider mb-4">IA</span>
    <h1 className="text-4xl font-bold leading-tight mb-4 text-white">Como Automatizar RH e Contratacao com IA</h1>
    <div className="flex items-center gap-5 text-sm text-slate-500"><span>2026-05-16</span><span>•</span><span>3 min</span></div>
  </div></div>
  <article className="max-w-3xl mx-auto px-6 py-12"><div className="prose prose-invert max-w-none">{content}</div></article>
</div>);}