import{Metadata}from'next';import Link from'next/link';
export const metadata:Metadata={title:'IA para vendas B2B: como automatizar prospeccao e follow-up - Automacao IA'};
export default function Page(){const content=`# Você busca leads, envia e-mail, espera resposta, esquece de follow-up, recomeça\n\n80% dos vendedores desistem após o primeiro "não". Lead precisa de **5 a 7 interações** para fechar. Cada etapa manual consome tempo e depende de memória.\n\n**IA para vendas B2B** automatiza prospecção e follow-up sem parecer robô.\n\n## A arquitetura ideal do seu agente de vendas\n\nVocê precisa de três componentes funcionando juntos.\n\n### Como funciona na prática:\n\n| Componente | O que faz | Exemplo |\n|------------|-----------|---------|\n| Canal de entrada | Recebe o lead | Telegram, WhatsApp, formulário |\n| Orquestrador | Conecta tudo | Make ou n8n |\n| IA | Qualifica e responde | OpenAI, Gemini, DeepSeek |\n\n**Ferramentas:** **Make** para conectar os blocos. **OpenAI** ou **DeepSeek** para inteligência. **Telegram** ou **WhatsApp** como canal.\n\n## Passo a passo: bot de vendas que qualifica automaticamente\n\nLead chega no Telegram. IA pergunta, analisa e decide se vale seguir.\n\n### Como configurar:\n\n| Etapa | O que acontece | Ação da IA |\n|-------|----------------|------------|\n| 1 | Lead envia "olá, quero saber sobre o produto" | Responde com perguntas de qualificação |\n| 2 | Lead responde: "dono de empresa, 10 funcionários" | Analisa perfil e decide se é lead quente |\n| 3 | Lead qualificado | Encaminha para vendedor humano |\n\n> **Dica prática:** Configure 3 perguntas de qualificação. Se o lead responder todas, é quente. Se não, entra em nutrição automática.\n\n> ---\n> **🚀 Quer automatizar a prospecção de vendas da sua empresa?** Teste grátis por 14 dias. [Comece agora](#)\n> ---\n\n## Follow-up automático que não parece robô\n\nLead pediu para pensar. Você esquece. IA lembra e envia mensagem personalizada no timing certo.\n\n### Como funciona:\n\n| Dia após contato | Mensagem da IA | Objetivo |\n|------------------|----------------|----------|\n| 1 dia | "Oi [nome], viu o material que enviei?" | Reforçar oferta |\n| 3 dias | "Uma dúvida que surgiu: [pergunta personalizada]" | Engajar com valor |\n| 7 dias | "Fechou com concorrente? Posso ajudar com [dor específica]" | Recuperar lead frio |\n\n> **Exemplo real:** Uma empresa de software usava follow-up automático com IA. A taxa de conversão de leads frios **subiu de 5% para 18%** em 3 meses.\n\n## Checklist para automatizar vendas B2B\n\n- [ ] Configure canal de entrada (Telegram, WhatsApp ou formulário)\n- [ ] Crie 3 perguntas de qualificação automática com IA\n- [ ] Implemente follow-up automático com 3 mensagens em timing diferente\n- [ ] Monitore a taxa de conversão de leads frios no primeiro mês`.split('\\n').map((l,i)=>{
  if(l.startsWith('## '))return<h2 key={i} className="text-2xl font-bold mt-10 mb-4 text-white">{l.slice(3)}</h2>;
  if(l.startsWith('### '))return<h3 key={i} className="text-xl font-semibold mt-8 mb-3 text-white">{l.slice(4)}</h3>;
  if(l.startsWith('|'))return<p key={i} className="font-mono text-xs text-slate-400 my-1">{l}</p>;
  if(l.startsWith('- [ ]'))return<p key={i} className="flex items-center gap-2 text-slate-300 my-1"><input type="checkbox" className="w-4 h-4 rounded accent-cyan-500" readOnly/>{l.slice(5)}</p>;
  if(l.startsWith('[')){const m=l.match(/\[(.+?)\]\((.+?)\)/);if(m)return<p key={i} className="my-2"><a href={m[2]} target="_blank" className="text-cyan-400 underline">{m[1]}</a></p>}
  if(!l.trim())return<br key={i}/>;return<p key={i} className="text-slate-300 leading-relaxed mb-2">{l}</p>;});
return(<div className="min-h-screen bg-[#0a0a0f]">
  <div className="border-b border-white/[0.04]"><div className="max-w-3xl mx-auto px-6 py-16">
    <Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-cyan-400 text-sm mb-6">← Voltar</Link>
    <span className="inline-block text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-400 font-medium uppercase tracking-wider mb-4">IA</span>
    <h1 className="text-4xl font-bold leading-tight mb-4 text-white">IA para vendas B2B: como automatizar prospeccao e follow-up</h1>
    <div className="flex items-center gap-5 text-sm text-slate-500"><span>2026-05-16</span><span>•</span><span>3 min</span></div>
  </div></div>
  <article className="max-w-3xl mx-auto px-6 py-12"><div className="prose prose-invert max-w-none">{content}</div></article>
</div>);}