import{Metadata}from'next';import Link from'next/link';
export const metadata:Metadata={title:'Chatbot com IA para Atendimento ao Cliente - Automacao IA'};
export default function Page(){const content=`# Cliente pergunta e você demora horas para responder\n\n"Quanto custa?" "Tem em estoque?" "Qual o prazo?" São as mesmas perguntas todo dia. Enquanto você não responde, o cliente vai para o concorrente.\n\nUm **chatbot com IA** responde na hora, 24 horas por dia, 7 dias por semana. Resolve **80% das perguntas** sem você tocar no celular.\n\n## O que você precisa para montar seu chatbot\n\n| Ferramenta | Função | Preço |\n|------------|--------|-------|\n| **WhatsApp Business API** | Canal de atendimento | Grátis (via provedor) |\n| **Make** | Orquestrador do fluxo | Grátis (1.000 op/mês) |\n| **DeepSeek** | IA para entender e responder | Grátis (500 req/dia) |\n| **Google Sheets** | Base de conhecimento | Grátis |\n\nTudo gratuito para começar. Você monta em uma tarde.\n\n## Passo a passo: WhatsApp + IA em 4 etapas\n\n### 1. Configure a entrada de mensagens\n\nNo Make, crie um cenário com trigger **Webhook**. Copie a URL gerada. Cole no provedor WhatsApp como endpoint.\n\nToda mensagem que chegar no WhatsApp será enviada para o Make.\n\n\`\`\`\nWhatsApp → Webhook Make → DeepSeek → Resposta\n\`\`\`\n\n### 2. Monte a base de conhecimento\n\nCrie uma planilha no Google Sheets com perguntas frequentes e respostas.\n\n| Palavra-chave | Resposta |\n|---------------|----------|\n| "preço", "quanto custa" | "Nossos planos começam em R$ 97/mês" |\n| "estoque", "disponível" | "Consulte disponibilidade no site" |\n| "prazo", "entrega" | "Prazo médio de 5 dias úteis" |\n\n---\n\n> **🚀 Quer o template pronto do chatbot?** Baixe grátis e configure em 30 minutos. [Comece agora](#)\n\n---\n\n### 3. Configure a IA para responder\n\nDeepSeek recebe a pergunta do cliente, consulta a base e gera a resposta. Se não encontrar, encaminha para você.\n\n**Regras de funcionamento:**\n\n- Pergunta conhecida → Resposta automática\n- Pergunta complexa → Encaminha para humano\n- Cliente irritado → Prioriza atendimento humano\n- Fora do horário → Responde com "retornaremos amanhã"\n\n### 4. Teste e refine\n\nEnvie 10 perguntas diferentes para o robô. Veja se respondeu certo. Ajuste a base de conhecimento.\n\n## 3 perguntas que seu chatbot precisa responder\n\n- "Quanto custa?" — Preços e planos\n- "Tem em estoque?" — Disponibilidade de produtos\n- "Qual o prazo?" — Prazo de entrega ou serviço\n\n## Checklist para seu primeiro chatbot\n\n- [ ] Crie conta no Make e no DeepSeek\n- [ ] Monte base de conhecimento no Sheets\n- [ ] Configure fluxo webhook → IA → resposta\n- [ ] Teste com 10 perguntas reais de clientes`.split('\\n').map((l,i)=>{
  if(l.startsWith('## '))return<h2 key={i} className="text-2xl font-bold mt-10 mb-4 text-white">{l.slice(3)}</h2>;
  if(l.startsWith('### '))return<h3 key={i} className="text-xl font-semibold mt-8 mb-3 text-white">{l.slice(4)}</h3>;
  if(l.startsWith('|'))return<p key={i} className="font-mono text-xs text-slate-400 my-1">{l}</p>;
  if(l.startsWith('- [ ]'))return<p key={i} className="flex items-center gap-2 text-slate-300 my-1"><input type="checkbox" className="w-4 h-4 rounded accent-cyan-500" readOnly/>{l.slice(5)}</p>;
  if(l.startsWith('[')){const m=l.match(/\[(.+?)\]\((.+?)\)/);if(m)return<p key={i} className="my-2"><a href={m[2]} target="_blank" className="text-cyan-400 underline">{m[1]}</a></p>}
  if(!l.trim())return<br key={i}/>;return<p key={i} className="text-slate-300 leading-relaxed mb-2">{l}</p>;});
return(<div className="min-h-screen bg-[#0a0a0f]">
  <div className="border-b border-white/[0.04]"><div className="max-w-3xl mx-auto px-6 py-16">
    <Link href="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-cyan-400 text-sm mb-6">\u2190 Voltar</Link>
    <span className="inline-block text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-400 font-medium uppercase tracking-wider mb-4">IA</span>
    <h1 className="text-4xl font-bold leading-tight mb-4 text-white">Chatbot com IA para Atendimento ao Cliente</h1>
    <div className="flex items-center gap-5 text-sm text-slate-500"><span>2026-05-16</span><span>\u2022</span><span>3 min</span></div>
  </div></div>
  <article className="max-w-3xl mx-auto px-6 py-12"><div className="prose prose-invert max-w-none">{content}</div></article>
</div>);}